<?xml version="1.0" encoding="utf-8"?><Database Name="Focus" EntityNamespace="Capture" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LOCALHOST\SQLEXPRESS;Initial Catalog=Focus;Integrated Security=True" SettingsObjectName="Capture.Properties.Settings" SettingsPropertyName="FocusConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.StreamMoments" Member="StreamMoments">
    <Type Name="StreamMoment">
      <Column Name="SnapshotTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Symbols" Member="Symbols">
    <Type Name="Symbol">
      <Column Name="SymbolID" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NChar(32)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Market" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.INSERTStreamMoment" Method="INSERTStreamMoment">
    <Parameter Name="param1" Type="System.DateTime" DbType="DateTime2" />
    <Parameter Name="param2" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
</Database>